import type ProductType from "../types/Product";

const products: ProductType[] = [
  {
    id: 1,
    name: "Kid Tapered Slim Fit Trouser",
    price: 38,
    reviews: [
      { reviewText: "Wow, I love this product", rating: 5 },
      { reviewText: "very good quality", rating: 4 },
    ],
    rating: 4.5,
    reviewCount: 2,
    shortDescription:
      "Slim-fit tapered trousers for kids with a modern and comfortable design.",
    longDescription:
      "These tapered trousers provide a sharp look while ensuring all-day comfort. Ideal for school, casual wear, or special occasions.",
    category: "kids",
    subCategory: "bottomwear",
    tags: ["kids", "trousers", "tapered", "casual"],
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    features: ["Soft Fabric", "Breathable", "Slim Fit"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png",
    ],
    bestseller: false,
    inStock: 1,
  },
  {
    id: 2,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 25,
    reviews: [{ reviewText: "Great fit!", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription:
      "Classic round neck t-shirt made from pure cotton for everyday comfort.",
    longDescription:
      "A wardrobe essential crafted from 100% cotton. Soft, breathable, and perfect for daily casual wear.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "t-shirt", "cotton", "basic"],
    availableSizes: ["M", "L", "XL", "XXL"],
    features: ["100% Cotton", "Breathable", "Soft"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 3,
    name: "Box Round Neck Pure Cotton T-shirt",
    price: 55,
    reviews: [{ reviewText: "Beautiful pattern", rating: 4 }],
    rating: 4,
    reviewCount: 1,
    shortDescription:
      "Boxy fit cotton t-shirt with a relaxed and modern silhouette.",
    longDescription:
      "Designed for a trendy oversized look, this boxy t-shirt offers comfort and breathability for everyday styling.",
    category: "women",
    subCategory: "topwear",
    tags: ["women", "t-shirt", "boxy", "cotton"],
    availableSizes: ["XS", "S", "M", "L"],
    features: ["Relaxed Fit", "Soft Cotton", "Breathable"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png",
    ],
    bestseller: true,
    inStock: 1,
  },
  {
    id: 4,
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 65,
    reviews: [{ reviewText: "Perfect stretch", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Relaxed fit jacket with a convenient zip-front design.",
    longDescription:
      "This stylish jacket is perfect for layering. Lightweight and comfortable, it suits both casual and semi-formal outfits.",
    category: "women",
    subCategory: "topwear",
    tags: ["women", "jacket", "zip", "casual"],
    availableSizes: ["S", "M", "L"],
    features: ["Zip Closure", "Lightweight", "Comfort Fit"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 5,
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 32,
    reviews: [{ reviewText: "Super soft inside", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Smart tapered trousers with a clean flat-front finish.",
    longDescription:
      "Perfect for office or formal occasions, these trousers offer a tailored look with enhanced comfort.",
    category: "men",
    subCategory: "bottomwear",
    tags: ["men", "trousers", "formal", "tapered"],
    availableSizes: ["30", "32", "34", "36"],
    features: ["Tailored Fit", "Comfort Fabric", "Durable"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img15.png",
    ],
    bestseller: false,
    inStock: 1,
  },
  {
    id: 6,
    name: "Girls Round Neck Cotton Top",
    price: 42,
    reviews: [{ reviewText: "Best for yoga!", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription:
      "Soft cotton top for girls with a comfortable round neckline.",
    longDescription:
      "Lightweight and breathable, this top is perfect for everyday comfort and casual wear.",
    category: "kids",
    subCategory: "topwear",
    tags: ["girls", "top", "cotton", "casual"],
    availableSizes: ["S", "M", "L"],
    features: ["Soft Cotton", "Lightweight", "Breathable"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 7,
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 48,
    reviews: [{ reviewText: "Good for office", rating: 4 }],
    rating: 4,
    reviewCount: 1,
    shortDescription: "Smart Oxford shirt for a clean and professional look.",
    longDescription:
      "Upgrade your wardrobe with this classic Oxford shirt. Designed for a tailored fit, it's perfect for office wear or formal occasions.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "shirt", "formal", "office"],
    availableSizes: ["M", "L", "XL"],
    features: ["Easy Iron", "Breathable", "Premium Fabric"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img51.png",
    ],
    bestseller: false,
    inStock: 1,
  },
  {
    id: 8,
    name: "Kid Tapered Slim Fit Trouser",
    price: 22,
    reviews: [{ reviewText: "Great value", rating: 4 }],
    rating: 4,
    reviewCount: 1,
    shortDescription: "Comfortable cotton shorts set, perfect for active kids.",
    longDescription:
      "Designed for everyday play, these shorts feature a soft fabric and elastic waistband for maximum comfort and flexibility.",
    category: "kids",
    subCategory: "bottomwear",
    tags: ["kids", "shorts", "summer", "casual"],
    availableSizes: ["XS", "S", "M"],
    features: ["Soft Cotton", "Elastic Waist", "Durable"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 9,
    name: "Man Printed Plain Cotton Shirtt",
    price: 89,
    reviews: [{ reviewText: "Very trendy", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Trendy oversized blazer for a modern and stylish look.",
    longDescription:
      "Add sophistication to any outfit with this oversized blazer. Perfect for both office wear and casual street style.",
    category: "men",
    subCategory: "topwear",
    tags: ["women", "blazer", "oversized", "fashion"],
    availableSizes: ["S", "M", "L"],
    features: ["Structured Fit", "Premium Fabric", "Stylish"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img39.png",
    ],
    bestseller: false,
    inStock: 1,
  },
  {
    id: 10,
    name: "Women Zip-Front Relaxed Fit Jackets",
    price: 58,
    reviews: [{ reviewText: "Lots of pockets", rating: 4 }],
    rating: 4,
    reviewCount: 1,
    shortDescription: "Durable cargo pants with multiple functional pockets.",
    longDescription:
      "Built for utility and style, these cargo pants are perfect for outdoor use or streetwear outfits.",
    category: "women",
    subCategory: "winterwear",
    tags: ["men", "cargo", "utility", "casual"],
    availableSizes: ["32", "34", "36"],
    features: ["Multi Pocket", "Durable", "Comfort Fit"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img36.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 11,
    name: "Men Elegant Wool Coat",
    price: 145,
    reviews: [{ reviewText: "Warm and elegant", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription:
      "Elegant wool coat designed for warmth and timeless style.",
    longDescription:
      "Crafted from a premium wool blend, this coat provides warmth while maintaining a sophisticated look.",
    category: "men",
    subCategory: "topwear",
    tags: ["women", "coat", "winter", "elegant"],
    availableSizes: ["S", "M", "L", "XL"],
    features: ["Wool Blend", "Warm", "Premium"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 12,
    name: "Kids Printed Casual T-Shirt",
    price: 18,
    reviews: [{ reviewText: "My son loves it", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Fun printed t-shirt for kids in vibrant colors.",
    longDescription:
      "Let your child stand out with this playful t-shirt. Made from soft cotton for all-day comfort.",
    category: "women",
    subCategory: "topwear",
    tags: ["kids", "t-shirt", "print", "casual"],
    availableSizes: ["S", "M", "L"],
    features: ["Soft Cotton", "Lightweight", "Durable"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img44.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 13,
    name: "Men Lightweight Rain Jacket",
    price: 75,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay protected from rain and wind with this breathable and lightweight jacket, perfect for outdoor use.",
    category: "men",
    subCategory: "winterwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img45.png",
    ],
    bestseller: false,
    inStock: 1,
  },
  {
    id: 14,
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 79,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "winterwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img28.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 15,
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 82,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img26.png",
    ],
    bestseller: false,
    inStock: 4,
  },
  {
    id: 16,
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 30,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img24.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 71,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 26,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img4.png",
    ],
    bestseller: true,
    inStock: 2,
  },
  {
    id: 18,
    name: "Women Round Neck Cotton Top",
    price: 40,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img1.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 19,
    name: "Girls Round Neck Cotton Top",
    price: 38,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img3.png",
    ],
    bestseller: false,
    inStock: 5,
  },
  {
    id: 20,
    name: "Women Zip-Front Relaxed Fit Jacket",
    price: 82,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img21.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 21,
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 82,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "bottomwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img17.png",
    ],
    bestseller: false,
    inStock: 7,
  },
  {
    id: 22,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 26,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img12.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 23,
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 28,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img18.png",
    ],
    bestseller: false,
    inStock: 2,
  },
  {
    id: 24,
    name: "Women Round Neck Cotton Top",
    price: 38,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img34.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 25,
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 80,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img48.png",
    ],
    bestseller: false,
    inStock: 6,
  },
  {
    id: 26,
    name: "Kid Tapered Slim Fit Trouser",
    price: 60,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "bottomwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img43.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 27,
    name: "Women Round Neck Cotton Top",
    price: 42,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img13.png",
    ],
    bestseller: true,
    inStock: 1,
  },
  {
    id: 28,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 34,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img31.png",
    ],
    bestseller: false,
    inStock: 5,
  },
  {
    id: 29,
    name: "Girls Round Neck Cotton Top",
    price: 40,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img16.png",
    ],
    bestseller: true,
    inStock: 2,
  },
  {
    id: 30,
    name: "Women Palazzo Pants with Waist Belt",
    price: 67,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "bottomwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img22.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 31,
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 84,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img52.png",
    ],
    bestseller: false,
    inStock: 2,
  },
  {
    id: 32,
    name: "Girls Round Neck Cotton Top",
    price: 48,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img9.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 33,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 46,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img11.png",
    ],
    bestseller: false,
    inStock: 3,
  },
  {
    id: 34,
    name: "Boy Round Neck Pure Cotton T-shirt",
    price: 36,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img19.png",
    ],
    bestseller: false,
    inStock: 2,
  },
  {
    id: 35,
    name: "Girls Round Neck Cotton Top",
    price: 60,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "kids",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img25.png",
    ],
    bestseller: true,
    inStock: 3,
  },
  {
    id: 36,
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 54,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "topwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img41.png",
    ],
    bestseller: false,
    inStock: 2,
  },
  {
    id: 37,
    name: "Women Palazzo Pants with Waist Belt",
    price: 52,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "women",
    subCategory: "bottomwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img20.png",
    ],
    bestseller: false,
    inStock: 0,
  },
  {
    id: 38,
    name: "Men Slim Fit Relaxed Denim Jacket",
    price: 77,
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    rating: 5,
    reviewCount: 1,
    shortDescription: "Lightweight waterproof jacket for rainy conditions.",
    longDescription:
      "Stay dry and comfortable with this breathable rain jacket. Designed for outdoor activities with reliable protection against wind and rain.",
    category: "men",
    subCategory: "winterwear",
    tags: ["men", "jacket", "rain", "outdoor"],
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Lightweight"],
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img40.png",
    ],
    bestseller: true,
    inStock: 1,
  },
];

export default products;
