import type ProductType from "../../src/types/products";

const products: ProductType[] = [
  {
    id: crypto.randomUUID(),
    name: "Kid Tapered Slim Fit Trouser",
    reviews: [
      { reviewText: "Wow, I love this product", rating: 5 },
      { reviewText: "very good quality", rating: 4 },
    ],
    price: 38,
    shortDescription:
      "A lightweight, slim-fit trouser for kids, perfect for casual wear.",
    longDescription:
      "These trousers offer a perfect blend of comfort and style. Made from breathable fabric, they ensure your child stays comfortable all day long while looking sharp.",
    availableSizes: ["S", "M", "L", "XL", "XXL"],
    features: [
      "100% Original product",
      "Cash on delivery is available",
      "7 days return policy",
    ],
    category: "Kid",
    subCategory: "Bottomwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img47.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Men Cotton Round Neck T-Shirt",
    reviews: [{ reviewText: "Great fit!", rating: 5 }],
    price: 25,
    shortDescription: "Pure cotton t-shirt with a classic round neck.",
    longDescription:
      "A must-have staple for every wardrobe. This t-shirt is crafted from premium cotton, providing ultimate softness and durability for everyday use.",
    availableSizes: ["M", "L", "XL", "XXL"],
    features: ["Premium Cotton", "Breathable", "Easy Wash"],
    category: "Men",
    subCategory: "Topwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img8.png",
    ],
    bestseller: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Women Floral Print Summer Dress",
    reviews: [{ reviewText: "Beautiful pattern", rating: 4 }],
    price: 55,
    shortDescription: "Lightweight floral dress for sunny days.",
    longDescription:
      "Stay cool and stylish with this elegant floral print dress. Designed with a flowing silhouette, it is perfect for garden parties or beach outings.",
    availableSizes: ["XS", "S", "M", "L"],
    features: ["Floral Print", "Lightweight Fabric", "Adjustable Straps"],
    category: "Women",
    subCategory: "Winterwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img14.png",
    ],
    bestseller: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Men Slim Fit Denim Jeans",
    reviews: [{ reviewText: "Perfect stretch", rating: 5 }],
    price: 65,
    shortDescription: "Classic blue slim-fit jeans with a bit of stretch.",
    longDescription:
      "Our signature slim-fit jeans are built for comfort. Featuring a modern cut and high-quality denim, they transition easily from day to night.",
    availableSizes: ["30", "32", "34", "36"],
    features: ["Stretch Denim", "Five-pocket style", "Durable"],
    category: "Men",
    subCategory: "Bottomwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img35.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Kid Hooded Sweatshirt",
    reviews: [{ reviewText: "Super soft inside", rating: 5 }],
    price: 32,
    shortDescription: "Warm and cozy hoodie for active kids.",
    longDescription:
      "Keep the cold at bay with this fleece-lined hooded sweatshirt. It features a kangaroo pocket and ribbed cuffs for a snug fit.",
    availableSizes: ["S", "M", "L"],
    features: ["Fleece Lined", "Kangaroo Pocket", "Machine Washable"],
    category: "Kid",
    subCategory: "Topwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img15.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Women High-Rise Leggings",
    reviews: [{ reviewText: "Best for yoga!", rating: 5 }],
    price: 42,
    shortDescription: "Opaque, high-waisted leggings for sport and leisure.",
    longDescription:
      "Designed for maximum flexibility, these high-rise leggings offer support and style. The moisture-wicking fabric keeps you dry during workouts.",
    availableSizes: ["S", "M", "L"],
    features: ["Squat-proof", "Moisture-wicking", "Hidden Pocket"],
    category: "Women",
    subCategory: "Winterwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img6.png",
    ],
    bestseller: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Men Formal Oxford Shirt",
    reviews: [{ reviewText: "Good for office", rating: 4 }],
    price: 48,
    shortDescription: "A crisp Oxford shirt for a professional look.",
    longDescription:
      "Elevate your workwear with this classic Oxford shirt. Tailored for a clean fit, it pairs perfectly with chinos or formal trousers.",
    availableSizes: ["M", "L", "XL"],
    features: ["Easy Iron", "Button-down collar", "Cotton Blend"],
    category: "Men",
    subCategory: "Topwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img51.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Kid Cotton Shorts Pack",
    reviews: [{ reviewText: "Great value", rating: 4 }],
    price: 22,
    shortDescription: "Pack of 2 comfortable cotton shorts.",
    longDescription:
      "Perfect for playtime, these shorts are made from soft cotton with an elastic waistband for an easy fit.",
    availableSizes: ["XS", "S", "M"],
    features: ["2-Pack", "Elastic Waist", "Durable"],
    category: "Kid",
    subCategory: "Bottomwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img50.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Women Oversized Blazer",
    reviews: [{ reviewText: "Very trendy", rating: 5 }],
    price: 89,
    shortDescription: "Modern oversized blazer for a chic silhouette.",
    longDescription:
      "Add a touch of sophistication to any outfit with this oversized blazer. Features structured shoulders and a smooth lining.",
    availableSizes: ["S", "M", "L"],
    features: ["Fully Lined", "Internal Pocket", "Modern Fit"],
    category: "Women",
    subCategory: "Winterwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img39.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Men Cargo Pants",
    reviews: [{ reviewText: "Lots of pockets", rating: 4 }],
    price: 58,
    shortDescription: "Rugged cargo pants for outdoor adventures.",
    longDescription:
      "Built for utility, these cargo pants feature multiple secure pockets and reinforced stitching for long-lasting wear.",
    availableSizes: ["32", "34", "36"],
    features: ["Multi-pocket", "Heavy-duty cotton", "Relaxed Fit"],
    category: "Men",
    subCategory: "Bottomwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img36.png",
    ],
    bestseller: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Women Wool Blend Coat",
    reviews: [{ reviewText: "Warm and elegant", rating: 5 }],
    price: 145,
    shortDescription: "Premium wool blend coat for winter.",
    longDescription:
      "A timeless piece for cold weather. This coat is made from a warm wool blend and features a classic lapel and belt.",
    availableSizes: ["S", "M", "L", "XL"],
    features: ["Wool Blend", "Thermal Lining", "Timeless Design"],
    category: "Women",
    subCategory: "Topwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img46.png",
    ],
    bestseller: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Kid Graphic Print T-Shirt",
    reviews: [{ reviewText: "My son loves it", rating: 5 }],
    price: 18,
    shortDescription: "Fun graphic t-shirt in bright colors.",
    longDescription:
      "Let your child's personality shine with our vibrant graphic tees. Soft cotton ensures it's comfortable for all-day wear.",
    availableSizes: ["S", "M", "L"],
    features: ["Eco-friendly ink", "Soft cotton", "No-tag neck"],
    category: "Kid",
    subCategory: "Winterwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img44.png",
    ],
    bestseller: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Men Waterproof Rain Jacket",
    reviews: [{ reviewText: "Stays dry", rating: 5 }],
    price: 75,
    shortDescription: "Lightweight and breathable rain protection.",
    longDescription:
      "This jacket is fully seam-sealed to keep water out while remaining breathable during physical activity.",
    availableSizes: ["M", "L", "XL"],
    features: ["Waterproof", "Windproof", "Packable"],
    category: "Men",
    subCategory: "Topwear",
    images: [
      "https://raw.githubusercontent.com/avinashdm/gs-images/main/forever/p_img45.png",
    ],
    bestseller: false,
  },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Women Pleated Midi Skirt",
  //   reviews: [{ reviewText: "Lovely movement", rating: 4 }],
  //   price: 45,
  //   shortDescription: "Elegant pleated skirt for office or dinner.",
  //   longDescription:
  //     "A versatile midi skirt with sharp pleats and a shimmering finish. Pairs perfectly with sweaters or blouses.",
  //   availableSizes: ["XS", "S", "M", "L"],
  //   features: ["High Waist", "Pleated Finish", "Silky Fabric"],
  //   category: "Women",
  //   subCategory: "Bottomwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: false,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Kid Denim Jacket",
  //   reviews: [{ reviewText: "Looks so cute", rating: 5 }],
  //   price: 40,
  //   shortDescription: "Classic denim jacket for kids.",
  //   longDescription:
  //     "The essential layer for any season. This denim jacket is rugged enough for play but stylish enough for photos.",
  //   availableSizes: ["S", "M", "L"],
  //   features: ["Metal buttons", "Distressed look", "Four pockets"],
  //   category: "Kid",
  //   subCategory: "Winterwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: false,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Men V-Neck Cashmere Sweater",
  //   reviews: [{ reviewText: "Incredible quality", rating: 5 }],
  //   price: 120,
  //   shortDescription: "Luxury cashmere sweater for ultimate comfort.",
  //   longDescription:
  //     "Knitted from the finest cashmere, this V-neck sweater offers unparalleled warmth and a premium feel.",
  //   availableSizes: ["M", "L", "XL"],
  //   features: ["100% Cashmere", "Soft touch", "Classic V-neck"],
  //   category: "Men",
  //   subCategory: "Topwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: true,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Women Skinny Fit Chinos",
  //   reviews: [{ reviewText: "Good office basic", rating: 4 }],
  //   price: 49,
  //   shortDescription: "Tailored chinos for a smart-casual look.",
  //   longDescription:
  //     "These chinos are crafted with a hint of stretch for a flattering skinny fit that doesn't compromise on comfort.",
  //   availableSizes: ["26", "28", "30", "32"],
  //   features: ["Breathable cotton", "Zip fly", "Slanted pockets"],
  //   category: "Women",
  //   subCategory: "Bottomwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: false,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Kid Pajama Set",
  //   reviews: [{ reviewText: "Very cozy", rating: 5 }],
  //   price: 28,
  //   shortDescription: "Soft cotton pajamas for a good night's sleep.",
  //   longDescription:
  //     "Made from 100% organic cotton, this pajama set is gentle on the skin and perfect for bedtime stories.",
  //   availableSizes: ["XS", "S", "M"],
  //   features: ["Organic Cotton", "Elastic cuffs", "Tag-free"],
  //   category: "Kid",
  //   subCategory: "Winterwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: true,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Men Performance Polo",
  //   reviews: [{ reviewText: "Great for golf", rating: 5 }],
  //   price: 35,
  //   shortDescription: "Moisture-wicking polo for active days.",
  //   longDescription:
  //     "Keep your cool on and off the course with our performance polo. Features anti-odor technology and UV protection.",
  //   availableSizes: ["L", "XL", "XXL"],
  //   features: ["Quick-dry", "UV Protection", "Stay-flat collar"],
  //   category: "Men",
  //   subCategory: "Topwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: false,
  // },
  // {
  //   id: crypto.randomUUID(),
  //   name: "Women Silk Blouse",
  //   reviews: [{ reviewText: "Feels expensive", rating: 5 }],
  //   price: 78,
  //   shortDescription: "Pure silk blouse with a modern cut.",
  //   longDescription:
  //     "A sophisticated addition to your wardrobe. This silk blouse features a hidden button placket and a beautiful drape.",
  //   availableSizes: ["S", "M", "L"],
  //   features: ["100% Silk", "Dry clean only", "Breathable"],
  //   category: "Women",
  //   subCategory: "Bottomwear",
  //   images: ["https://via.placeholder.com"],
  //   bestseller: false,
  // },
];

export default products;
